/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
interface apb_interface (input pclk, presetn);

    logic[31:0] paddr;
	logic[31:0] pwdata;
	logic psel;
	logic pwrite;
	logic penable;
	logic[31:0] prdata;
	logic pslverr;
	logic pready;
	

    // modport port(
    // input   pclk,
    // input   presetn,
    // |-SIGNAL_NAME_PORT-|);

endinterface
