/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
class apb_transaction extends uvm_sequence_item;

    logic[31:0] data;
	logic[31:0] addr;
	logic rw;
	logic slverr;
	

    `uvm_object_utils_begin(apb_transaction)
        `uvm_field_int(data, UVM_ALL_ON|UVM_HEX)
		`uvm_field_int(addr, UVM_ALL_ON|UVM_HEX)
		`uvm_field_int(rw, UVM_ALL_ON|UVM_HEX)
		`uvm_field_int(slverr, UVM_ALL_ON|UVM_HEX)
		
    `uvm_object_utils_end

    function new(string name="apb_transaction");
        super.new(name);
    endfunction: new

    function string convert2string();
        return $sformatf("{{ data, addr, rw, slverr}}", data, addr, rw, slverr);
    endfunction
endclass: apb_transaction
