/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
class apbTest_test extends uvm_test;
    arith_env env_h;
    apbSequence_sequence seq_0;
	

    `uvm_component_utils(apbTest_test)

    function new(string name, uvm_component parent = null);
        super.new(name, parent);
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env_h = arith_env::create("env_h", this);
		
        seq0 = apbSequence_sequence::create("seq0", this);
		
    endfunction

    task run_phase(uvm_phase phase);
        seq0.start(env_h.apb_agt.seqr);
		
    endtask: run_phase

endclass:apbTest_test
