/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
module top;
    import uvm_pkg::*;
    import arith_pkg::*;
    logic pclk;
	
    logic presetn;
		
    localparam P_PCLK = 90ns;
	
    localparam P_PRESETN = 3e12ns;
	
    initial begin

        presetn <= 1;
        pclk <= 0;

        #(180);
        presetn = 0; 
        #(180) presetn = 1;
		
    end
    always begin
      #(P_PCLK/2) pclk = ~pclk;
    end
	
    always begin
      #(P_PRESETN) presetn = 0; 
      #(180) presetn = 1;
    end
    apb_interface apb_if_if_top (
		.pclk(pclk), .presetn(presetn)
	);
		
    arith_wrapper dut(
      .apb_if_if(apb_if_if_top),
      .pclk(pclk),
      .presetn(presetn)
    );
    initial begin
        `ifdef XCELIUM
        $recordvars();
        `endif
        `ifdef VCS
        $vcdpluson;
        `endif
        `ifdef QUESTA
        $wlfdumpvars();
        set_config_int("*", "recording_detail", 1);
        `endif
        uvm_config_db#(virtual apb_interface)::set(null, "*.env_h.apb_agt.*", "VIRTUAL_IF", apb_if_if_top);
		
        run_test();
    end
endmodule
