/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
module arith_wrapper (
    apb_interface apb_if_if,
	input pclk,
	input presetn
    );

    arith arith_instance (
        .paddr(apb_if_if.paddr) ,
		.pwdata(apb_if_if.pwdata) ,
		.psel(apb_if_if.psel) ,
		.pwrite(apb_if_if.pwrite) ,
		.penable(apb_if_if.penable) ,
		.prdata(apb_if_if.prdata) ,
		.pslverr(apb_if_if.pslverr) ,
		.pready(apb_if_if.pready) ,
		.pclk(pclk),
		.presetn(presetn)
    );


endmodule
