/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
class arith_scoreboard extends uvm_scoreboard;

  arithRefmod_refmod arithRfm_rfm;
	
  uvm_in_order_class_comparator #(apb_transaction) arithComp;
	
  uvm_analysis_port #(apb_transaction) apb_agt_to_arithRfm_rfm;
	uvm_analysis_port #(apb_transaction) apb_agt_to_arithComp;
	
  `uvm_component_utils(arith_scoreboard)

  function new(string name = "scoreboard", uvm_component parent = null);
    super.new(name, parent);
    apb_agt_to_arithRfm_rfm= new("apb_agt_to_arithRfm_rfm", this);
		apb_agt_to_arithComp= new("apb_agt_to_arithComp", this);
		
  endfunction:new

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    arithRfm_rfm = arithRefmod_refmod::create("arithRfm_rfm", this);
		
    arithComp = uvm_in_order_class_comparator #(apb_transaction)::create("arithComp", this);
		
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    apb_agt_to_arithRfm_rfm.connect(arithRfm_rfm.from_apb_agt);
		apb_agt_to_arithComp.connect(arithComp.before_export);
		arithRfm_rfm.arithRfm_to_arithComp.connect(arithComp.after_export);
		
  endfunction
endclass:arith_scoreboard
