/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
class arith_env extends uvm_env;

    apb_agent apb_agt;
	
    arith_scoreboard arith_scb;
	
    

    `uvm_component_utils(arith_env)

    function new(string name, uvm_component parent = null);
        super.new(name, parent);
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        apb_agt = apb_agent::create("apb_agt", this);
		
        arith_scb = arith_scoreboard::create("arith_scb", this);
		
        
    endfunction

    virtual function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);

        apb_agt.ap_req.connect(arith_scb.apb_agt_to_arithRfm_rfm);
		apb_agt.ap_resp.connect(arith_scb.apb_agt_to_arithComp);
		

    endfunction

    virtual function void end_of_elaboration_phase(uvm_phase phase);
        super.end_of_elaboration_phase(phase);
    endfunction

endclass
