/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
class arithRefmod_refmod extends uvm_component;
    `uvm_component_utils(arithRefmod_refmod_refmod)

    apb_transaction req_0;
	
    apb_transaction resp_0;
	
    uvm_tlm_analysis_fifo #(apb_transaction) from_apb_agt;
	
    uvm_analysis_export #(apb_transaction) arithRfm_to_arithComp;
	

    function new(string name = "arithRefmod_refmod_refmod", uvm_component parent);
        super.new(name, parent);
        from_apb_agt = new("from_apb_agt", this);
		arithRfm_to_arithComp = new("arithRfm_to_arithComp", this);
		
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        req_0 = new("req_0", this);
		resp_0 = new("resp_0", this);
		
    endfunction: build_phase

    virtual task run_phase(uvm_phase phase);
        super.run_phase(phase);
        forever begin
            refmod_task()
        end
    endtask: run_phase

    task refmod_task();
        // Add your logic here

        

    endtask : refmod_task

endclass: arithRefmod_refmod
