/**
  ******************************************************************************
  * File automatic generated by XGeneratorTB software
  ******************************************************************************
**/
module arith (
        input logic pclk,
		input logic presetn,
		input logic[31:0] paddr,
		input logic[31:0] pwdata,
		input logic psel,
		input logic pwrite,
		input logic pwrite,
		input logic penable,
		output logic[31:0] prdata,
		output logic pslverr,
		output logic pready
    );

    


endmodule